[package]
name = "kamaji"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
axum-extra = { version = "0.5.0", features = ["spa"] }
deadpool-diesel = { version = "0.4.1", features = ["mysql"] }
default-env = "0.1.1"
diesel = { version = "2.0.3", features = ["mysql"] }
dotenvy = "0.15.6"
tokio = { version = "1.24.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.3.5", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
