[package]
name = "kamaji"
version = "0.1.0"
edition = "2021"
authors = ["Carl Knapp <hello@carlknapp.dev>"]

[dependencies]
axum = { version = "0.7.2", default-features = false, features = [
	"tokio",
	"http2",
] }
default-env = "0.1.1"
dotenvy = "0.15.6"
oauth2 = "4.3.0"
sqlx = { version = "0.7", features = [
	"migrate",
	"mysql",
	"runtime-tokio",
	"sqlite",
	"tls-rustls",
] }
tokio = { version = "1.24.1", features = ["macros"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "trace", "compression-br"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-unwrap = { version = "0.10.0", default-features = false }

[[bin]]
name = "kamaji"
path = "./src/server/main.rs"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
