services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25000:25000"
    volumes:
      - ..:/workspaces/kamaji
    stdin_open: true

  db:
    image: mariadb:10.9.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: kamaji
      MARIADB_USER: kamaji
      MARIADB_PASSWORD: kamaji

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: kamaji
      PMA_PASSWORD: kamaji
      UPLOAD_LIMIT: 50M