version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: kamaji
      MARIADB_USER: kamaji
      MARIADB_PASSWORD: kamaji

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_USER: kamaji
      PMA_PASSWORD: kamaji
      UPLOAD_LIMIT: 50M
      APACHE_PORT: 8080

volumes:
  mysql-data:
